/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ConfigTools: typeof import('./src/components/WindowTitleBar/ConfigTools/index.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LockScreen: typeof import('./src/components/LockScreen/index.vue')['default']
    LockScreenPage: typeof import('./src/components/LockScreen/LockScreenPage.vue')['default']
    LockTimeConfigDialog: typeof import('./src/components/WindowTitleBar/ConfigTools/LockTimeConfigDialog.vue')['default']
    ShowWebWindow: typeof import('./src/components/ShowWebWindow.vue')['default']
    TabsBar: typeof import('./src/components/TabsBar.vue')['default']
    WebWindow: typeof import('./src/components/WebWindow.vue')['default']
    WindowTitleBar: typeof import('./src/components/WindowTitleBar/index.vue')['default']
  }
}
